name: "Docker Image Artifact Download"
description: "Downloads docker image artifact uploaded from another job in same workflow"
inputs:
  image:
    description: Docker image to download
    required: true
outputs:
  download_path:
    description: Download path of the content of the artifact
runs:
  using: "node16"
  main: "dist/index.js"
