name: E2E Test
on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "master"
  workflow_dispatch:
jobs:
  upload-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build test image
        run: |
          docker build -t test_image:${{ github.run_id }} -<<EOF
            FROM busybox
            RUN touch abc.txt
          EOF

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "test_image:${{ github.run_id }}"

  run-e2e-test:
    needs: upload-test-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download image
        uses: ./
        with:
          image: "test_image:${{ github.run_id }}"

      - name: Test docker image is present
        run: |
          docker image inspect test_image:${{ github.run_id }}
